apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cln.fullname" . }}-traefix
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Headers(`X-Node`, `{{ include "cln.fullname" .}}`)
      kind: Rule
      services:
        - name: {{ include "cln.fullname" . }}
          port: client
          scheme: h2c
  # tls:
  #   certResolver: letsencrypt-prod
  #   domains:
  #     - main: id.example.com
