apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cln.fullname" . }}-client
  namespace: default
spec:
  entryPoints:
    - grpc
  routes:
    - match: Headers(`X-Node`, `{{ include "cln.fullname" .}}`)
      kind: Rule
      services:
        - name: {{ include "cln.fullname" . }}
          port: client
          scheme: h2c
  # tls:
  #   certResolver: letsencrypt-prod
  #   domains:
  #     - main: id.example.com
{{- if .Values.gRPCEntryPoint }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "cln.fullname" . }}-direct-grpc
  namespace: default
spec:
  entryPoints:       
    - {{ .Values.gRPCEntryPoint }}
  routes:             
    - match: HostSNI(`*`)
      services:  
        - name: {{ include "cln.fullname" . }}
          port: grpc
  tls:              
    passthrough: true
{{- end}}