apiVersion: v1
kind: Service
metadata:
  name: {{ include "cln.fullname" . }}
  labels:
    {{- include "cln.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: peer
      targetPort: peer
      port: {{ .Values.port }}
    - name: grpc
      targetPort: grpc
      port: {{ .Values.gRPCPort }}
    - name: client
      targetPort: client
      port: {{ .Values.clientPort }}
  selector:
    {{- include "cln.selectorLabels" . | nindent 4 }}