apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cln.fullname" . }}
  labels:
    {{- include "cln.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cln.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cln.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: clientcerts
          {{- if .Values.clnHostPath }}
          hostPath:
            path: {{ .Values.clnHostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: clientcerts
              mountPath: /root/.lightning
          ports:
            - name: peer
              containerPort: {{ .Values.port }}
            - name: grpc
              containerPort: {{ .Values.gRPCPort }}
          args:
            - --grpc-port={{ .Values.gRPCPort }}
            - --network={{ .Values.network }}
            - --bitcoin-rpcuser={{ .Values.bitcoind.rpcUser }}
            - --bitcoin-rpcpassword={{ .Values.bitcoind.rpcPass }}
            - --bitcoin-rpcconnect={{ .Values.bitcoind.rpcHost }}
            - --bitcoin-rpcport={{ .Values.bitcoind.rpcPort }}
            - --bitcoin-retry-timeout=600
        - name: {{ .Chart.Name }}-client
          image: {{ .Values.clientImage.repository }}:{{ .Values.clientImage.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: clientcerts
              mountPath: /cln
          ports:
            - name: client
              containerPort: {{ .Values.clientPort }}
          args:
            - -clientcert=/cln/regtest/client.pem
            - -clientkey=/cln/regtest/client-key.pem
            - -cacert=/cln/regtest/ca.pem
            - -grpcport={{ .Values.gRPCPort }}
            - -grpcaddress={{ include "cln.fullname" . }}
