releases:
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
  - name: alice
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint1
  - name: bob
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint2
  - name: carol
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint3
  - name: dave
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint4
