repositories:
  - name: traefik
    url: https://traefik.github.io/charts
releases:
  - name: traefik
    chart: traefik/traefik
    namespace: sl-traefik
    values:
      - ../../charts/traefik-values.yml
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
    values:
      - clientImage:
          repository: bitcoind-client
  - name: cln1
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint1
      - clientImage:
          repository: "cln-client"
  - name: cln2
    namespace: sl
    chart: ../../charts/cln
    values:
      - clientImage:
          repository: cln-client
  - name: lnd1
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint1
      - clientImage:
          repository: lnd-client
  - name: lnd2
    namespace: sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: lnd-client
