# uses local charts in the charts directory but images from docker hub
releases:
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
    values:
      - rpcEntryPoint: endpoint37
      - zmqPubBlockEntryPoint: endpoint38
      - zmqPubTxEntryPoint: endpoint39
  - name: alice
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint1
  - name: bob
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint2
  - name: carol
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint3
  - name: dave
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint4
