# uses the local charts in the charts directory and images available locally
releases:
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
    values:
      - clientImage:
          repository: scalingln/bitcoind-client
          pullPolicy: IfNotPresent
      - autoGen: true
      - rpcEntryPoint: endpoint37
      - zmqPubBlockEntryPoint: endpoint38
      - zmqPubTxEntryPoint: endpoint39
  - name: cln1
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint1
      - clientImage:
          repository: scalingln/cln-client
          pullPolicy: IfNotPresent
  - name: cln2
    namespace: sl
    chart: ../../charts/cln
    values:
      - clientImage:
          repository: scalingln/cln-client
          pullPolicy: IfNotPresent
      - gRPCEntryPoint: endpoint2
  - name: lnd1
    namespace: sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: scalingln/lnd-client
          pullPolicy: IfNotPresent
      - gRPCEntryPoint: endpoint3
  - name: lnd2
    namespace: sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: scalingln/lnd-client
          pullPolicy: IfNotPresent
      - gRPCEntryPoint: endpoint4
