# uses the local charts in the charts directory and images available locally
releases:
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
    values:
      - clientImage:
          repository: bitcoind-client
          pullPolicy: IfNotPresent
  - name: cln1
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint1
      - clientImage:
          repository: cln-client
          pullPolicy: IfNotPresent
  - name: cln2
    namespace: sl
    chart: ../../charts/cln
    values:
      - clientImage:
          repository: cln-client
          pullPolicy: IfNotPresent
  - name: lnd1
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint1
      - clientImage:
          repository: lnd-client
          pullPolicy: IfNotPresent
  - name: lnd2
    namespace: sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: lnd-client
          pullPolicy: IfNotPresent
