# uses the local charts in the charts directory and images available locally
# uses custom namespace (note that the endpoints are changed to avoid conflicts)
releases:
  - name: bitcoind
    namespace: my-other-sl
    chart: ../../charts/bitcoind
    values:
      - clientImage:
          repository: bitcoind-client
          pullPolicy: IfNotPresent
      - autoGen: true
      - rpcEntryPoint: endpoint27
      - zmqPubBlockEntryPoint: endpoint28
      - zmqPubTxEntryPoint: endpoint29
  - name: cln1
    namespace: my-other-sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint20
      - clientImage:
          repository: cln-client
          pullPolicy: IfNotPresent
  - name: lnd1
    namespace: my-other-sl
    chart: ../../charts/lnd
    values:
      - clientImage:
          repository: lnd-client
          pullPolicy: IfNotPresent
      - gRPCEntryPoint: endpoint21
