# uses images from our public charts repository and images from docker hub
# this file could be used either stand alone with helmfile or with our cli binary from https://github.com/scaling-lightning/scaling-lightning/releases
# no need to clone the source code of project to use this file
repositories:
  - name: scalinglightning
    url: https://charts.scalinglightning.com
releases:
  - name: bitcoind
    namespace: sl
    chart: scalinglightning/bitcoind
  - name: cln1
    namespace: sl
    chart: scalinglightning/cln
    values:
      - gRPCEntryPoint: endpoint1
  - name: cln2
    namespace: sl
    chart: scalinglightning/cln
    values:
      - gRPCEntryPoint: endpoint2
  - name: lnd1
    namespace: sl
    chart: scalinglightning/lnd
    values:
      - gRPCEntryPoint: endpoint3
  - name: lnd2
    namespace: sl
    chart: scalinglightning/lnd
    values:
      - gRPCEntryPoint: endpoint4
