# uses public charts from helm repo and images from dockerhub
# specifies specific version of chart and image
# use with either library or cli of same version for maximum compatibility
repositories:
  - name: scalinglightning
    url: https://charts.scalinglightning.com
releases:
  - name: bitcoind
    namespace: sl
    chart: scalinglightning/bitcoind
    version: 0.0.33
    values:
      - clientImage:
          tag: 0.0.33
  - name: alice
    namespace: sl
    chart: scalinglightning/cln
    version: 0.0.33
    values:
      - clientImage:
          tag: 0.0.33
      - gRPCEntryPoint: endpoint1
  - name: bob
    namespace: sl
    chart: scalinglightning/cln
    version: 0.0.33
    values:
      - clientImage:
          tag: 0.0.33
      - gRPCEntryPoint: endpoint2
  - name: carol
    namespace: sl
    chart: scalinglightning/lnd
    version: 0.0.33
    values:
      - clientImage:
          tag: 0.0.33
      - gRPCEntryPoint: endpoint3
  - name: dave
    namespace: sl
    chart: scalinglightning/lnd
    version: 0.0.33
    values:
      - clientImage:
          tag: 0.0.33
      - gRPCEntryPoint: endpoint4
