# uses local charts in the charts directory but images from docker hub
releases:
  - name: bitcoind
    namespace: sl
    chart: ../../charts/bitcoind
    values:
      - volume:
          size: "1Gi"
  - name: alice
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint1
      - image:
          tag: v23.05.1
      - volume:
          size: "1Gi"
  - name: bob
    namespace: sl
    chart: ../../charts/cln
    values:
      - gRPCEntryPoint: endpoint2
  - name: carol
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint3
      - image:
          tag: v0.17.0-beta.rc3
      - volume:
          size: "1Gi"
  - name: dave
    namespace: sl
    chart: ../../charts/lnd
    values:
      - gRPCEntryPoint: endpoint4
