apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lnd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lnd.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: tlsmacaroon
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tlsmacaroon
              mountPath: /root/.lnd
          ports:
            - name: peer
              containerPort: {{ .Values.port }}
            - name: grpc
              containerPort: {{ .Values.gRPCPort }}
            - name: rest
              containerPort: {{ .Values.restPort }}
          args:
            - --noseedbackup
            - --listen=0.0.0.0:{{ .Values.port }}
            - --rpclisten=0.0.0.0:{{ .Values.gRPCPort }}
            - --restlisten=0.0.0.0:{{ .Values.restPort }}
            {{- if eq "regtest" .Values.network  }}
            - --bitcoin.regtest
            {{- end }}
            - --bitcoin.active
            - --bitcoin.node=bitcoind
            - --bitcoind.rpchost={{ .Values.rpcHost }}
            - --bitcoind.rpcuser={{ .Values.rpcUser }}
            - --bitcoind.rpcpass={{ .Values.rpcPass }}
            - --bitcoind.zmqpubrawblock=tcp://{{ .Values.rpcHost }}:{{ .Values.zmqPubBlockPort }}
            - --bitcoind.zmqpubrawtx=tcp://{{ .Values.rpcHost }}:{{ .Values.zmqPubTxPort }}
        - name: {{ .Chart.Name }}-client
          image: "lnd-client"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tlsmacaroon
              mountPath: /lnd
          ports:
            - name: http
              containerPort: 8080
          ports:
            - name: client
              containerPort: {{ .Values.clientPort }}
          args:
            - -tlsfilepath=/lnd/tls.cert
            - -macaroonfilepath=/lnd/data/chain/bitcoin/regtest/admin.macaroon
            - -grpcport=10009
            - -grpcaddress=lnd
