apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "lnd.fullname" . }}-client
spec:
  entryPoints:
    - grpc
  routes:
    - match: Headers(`X-Node`, `{{ include "lnd.fullname" .}}`)
      kind: Rule
      services:
        - name: {{ include "lnd.fullname" . }}
          port: client
          scheme: h2c
{{- if .Values.gRPCEntryPoint }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "lnd.fullname" . }}-direct-grpc
spec:
  entryPoints:       
    - {{ .Values.gRPCEntryPoint }}
  routes:             
    - match: HostSNI(`*`)
      services:  
        - name: {{ include "lnd.fullname" . }}
          port: grpc
  tls:              
    passthrough: true
{{- end}}