apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: peer
      targetPort: peer
      port: {{ .Values.port }}
    - name: grpc
      targetPort: grpc
      port: {{ .Values.gRPCPort }}
    - name: rest
      targetPort: rest
      port: {{ .Values.restPort }}
    - name: client
      targetPort: client
      port: {{ .Values.clientPort }}
  selector:
    {{- include "lnd.selectorLabels" . | nindent 4 }}
