apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lnd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lnd.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: data
          {{- if .Values.volume.size }}
          persistentVolumeClaim:
            claimName: {{ include "lnd.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /root/.lnd
          ports:
            - name: peer
              containerPort: {{ .Values.port }}
            - name: grpc
              containerPort: {{ .Values.gRPCPort }}
            - name: rest
              containerPort: {{ .Values.restPort }}
          args:
            - --noseedbackup
            - --listen=0.0.0.0:{{ .Values.port }}
            - --rpclisten=0.0.0.0:{{ .Values.gRPCPort }}
            - --restlisten=0.0.0.0:{{ .Values.restPort }}
            {{- if eq "regtest" .Values.network  }}
            - --bitcoin.regtest
            {{- end }}
            - --bitcoin.active
            - --bitcoin.node=bitcoind
            - --bitcoind.rpchost={{ .Values.bitcoind.rpcHost }}
            - --bitcoind.rpcuser={{ .Values.bitcoind.rpcUser }}
            - --bitcoind.rpcpass={{ .Values.bitcoind.rpcPass }}
            - --bitcoind.zmqpubrawblock=tcp://{{ .Values.bitcoind.rpcHost }}:{{ .Values.bitcoind.zmqPubBlockPort }}
            - --bitcoind.zmqpubrawtx=tcp://{{ .Values.bitcoind.rpcHost }}:{{ .Values.bitcoind.zmqPubTxPort }}
            - --tlsextradomain={{ include "lnd.fullname" . }}
            - --accept-keysend
        - name: {{ .Chart.Name }}-client
          image: {{ .Values.clientImage.repository }}:{{ .Values.clientImage.tag | default "latest" }}
          imagePullPolicy: {{ .Values.clientImage.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /lnd
          ports:
            - name: http
              containerPort: 8080
            - name: client
              containerPort: {{ .Values.clientPort }}
          args:
            - -tlsfilepath=/lnd/tls.cert
            - -macaroonfilepath=/lnd/data/chain/bitcoin/regtest
            - -grpcport=10009
            - -grpcaddress={{ include "lnd.fullname" . }}
