apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "bitcoind.fullname" . }}-traefix
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Headers(`X-Node`, `{{ include "bitcoind.fullname" .}}`)
      kind: Rule
      services:
        - name: {{ include "bitcoind.fullname" . }}
          port: client