apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "bitcoind.fullname" . }}-client
spec:
  entryPoints:
    - grpc
  routes:
    - match: Headers(`X-Node`, `{{ include "bitcoind.fullname" .}}`)
      kind: Rule
      services:
        - name: {{ include "bitcoind.fullname" . }}
          port: client
          scheme: h2c