apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "bitcoind.fullname" . }}-client
spec:
  entryPoints:
    - grpc
  routes:
    - match: Header(`X-Node`, `{{ include "bitcoind.fullname" .}}`)
      kind: Rule
      services:
        - name: {{ include "bitcoind.fullname" . }}
          port: client
          scheme: h2c
{{- if .Values.rpcEntryPoint }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "bitcoind.fullname" . }}-direct-rpc
spec:
  entryPoints:
    - {{ .Values.rpcEntryPoint }}
  routes:
    - match: HostRegexp(`.*`)
      kind: Rule
      services:
        - name: {{ include "bitcoind.fullname" . }}
          port: rpc
{{- end}}
{{- if .Values.zmqPubBlockEntryPoint }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "bitcoind.fullname" . }}-direct-zmq-pub-block
spec:
  entryPoints:
    - {{ .Values.zmqPubBlockEntryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "bitcoind.fullname" . }}
          port: zmqpubrawblock
{{- end}}
{{- if .Values.zmqPubTxEntryPoint }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "bitcoind.fullname" . }}-direct-zmq-pub-tx
spec:
  entryPoints:
    - {{ .Values.zmqPubTxEntryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "bitcoind.fullname" . }}
          port: zmqpubrawtx
{{- end}}