with-expecter: true
packages:
  github.com/scaling-lightning/scaling-lightning/pkg/network:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mock_{{.InterfaceName}}_test.go"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      LightningNodeInterface:
      BitcoinNodeInterface:
  github.com/scaling-lightning/scaling-lightning/pkg/standardclient/common:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mock_{{.InterfaceName}}_test.go"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      CommonClient:
  github.com/scaling-lightning/scaling-lightning/pkg/standardclient/bitcoin:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mock_{{.InterfaceName}}_test.go"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      BitcoinClient:
  github.com/scaling-lightning/scaling-lightning/pkg/standardclient/lightning:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mock_{{.InterfaceName}}_test.go"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      LightningClient:
