inpackage: true
with-expecter: true
packages:
  github.com/scaling-lightning/scaling-lightning/pkg/network:
    config:
      dir: "mocks/"
      outpkg: mocks
      exported: true
    interfaces:
      SLNetworkInterface:
      LightningNodeInterface:
      Node:
