# testonly: true # try again in future
with-expecter: true
packages:
  github.com/scaling-lightning/scaling-lightning/pkg/network:
    config:
      outpkg: "mocks"
      dir: "pkg/network/mocks/"
    interfaces:
      SLNetworkInterface:
        config:
          # replace-type:
          #   - github.com/scaling-lightning/scaling-lightning/pkg/network.Node=github.com/scaling-lightning/scaling-lightning/pkg/network/mocks.MockNode
