# Default values for helm.
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

image:
  repository: ruimarinho/bitcoin-core
  tag: 24
  pullPolicy: IfNotPresent

rpcPort: 8332
rpcPortTest: 18443

network: regtest
