# Default values for helm.
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

image:
  repository: ruimarinho/bitcoin-core
  tag: 24
  pullPolicy: IfNotPresent

clientImage:
  repository: scalingln/bitcoind-client
  tag: latest
  pullPolicy: IfNotPresent

rpcPort: 8332
rpcPortTest: 18443

zmqPubBlockPort: 28332
zmqPubTxPort: 28333

clientPort: 8181

network: regtest
