name: Release charts, docker images and binaries

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    uses: ./.github/workflows/run-all-tests.yml
    secrets: inherit
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        name: Get tag
        id: tagName
        with:
          tagRegex: "v?(.+)" # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
    outputs:
      tag: ${{ steps.tagName.outputs.tag }}
  bitcoind-sidecar-image:
    if: false
    needs: [test]
    uses: ./.github/workflows/build-and-push-sidecar.yml
    secrets: inherit
    with:  
      image_name: scalingln/bitcoind-client
      artifact_name: bitcoindclient
      dockerfile: ./clients/bitcoind/Dockerfile
  cln-sidecar-image:
    if: false
    needs: [test]
    uses: ./.github/workflows/build-and-push-sidecar.yml
    secrets: inherit
    with:  
      image_name: scalingln/cln-client
      artifact_name: clnclient
      dockerfile: ./clients/cln/Dockerfile
  lnd-sidecar-image:
    if: false
    needs: [test]
    uses: ./.github/workflows/build-and-push-sidecar.yml
    secrets: inherit
    with:  
      image_name: scalingln/lnd-client
      artifact_name: lndclient
      dockerfile: ./clients/lnd/Dockerfile
  helm-charts:
    permissions:
     contents: write
    runs-on: ubuntu-latest
    name: Deploy Helm charts
    needs: [test, get-tag]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Package charts
        run: helm package charts/bitcoind charts/cln charts/lnd --version ${{ needs.get-tag.outputs.tag }} --destination charts/dist
      - name: Index charts
        run: helm repo index charts/dist --url https://charts.scalinglightning.com
      - run: |
          git stash
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - run: |
          git stash pop
      - name: Commit published charts to repo
        uses: EndBug/add-and-commit@v9
