on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-binary:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: amd64
        pre_command: |
            go generate cmd/build/version.go
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        pre_command: |
            go generate cmd/build/version.go
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: arm64
        pre_command: |
            go generate cmd/build/version.go
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm64
        pre_command: |
            go generate cmd/build/version.go
  publish-bitcoind-sidecar-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: olegtarasov/get-tag@v2.1.2
      name: Get tag
      id: tagName
      with:
        tagRegex: "v?(.+)" # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker tag and push latest
      run: |
        docker pull scalingln/bitcoind-client:${{ steps.tagName.outputs.tag }}
        docker tag scalingln/bitcoind-client:${{ steps.tagName.outputs.tag }} scalingln/bitcoind-client:latest
        docker push scalingln/bitcoind-client:latest
  publish-cln-sidecar-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: olegtarasov/get-tag@v2.1.2
      name: Get tag
      id: tagName
      with:
        tagRegex: "v?(.+)" # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker tag and push latest
      run: |
        docker pull scalingln/cln-client:${{ steps.tagName.outputs.tag }}
        docker tag scalingln/cln-client:${{ steps.tagName.outputs.tag }} scalingln/cln-client:latest
        docker push scalingln/cln-client:latest
  lnd-sidecar-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: olegtarasov/get-tag@v2.1.2
      name: Get tag
      id: tagName
      with:
        tagRegex: "v?(.+)" # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker tag and push latest
      run: |
        docker pull scalingln/lnd-client:${{ steps.tagName.outputs.tag }}
        docker tag scalingln/lnd-client:${{ steps.tagName.outputs.tag }} scalingln/lnd-client:latest
        docker push scalingln/lnd-client:latest